name: Truffle Hog Secret Detection
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  hog:
    runs-on: ubuntu-latest
    name: hog
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: TruffleHog
        run: docker run --rm -v ${{ github.workspace }}:/tmp -w /tmp ghcr.io/trufflesecurity/trufflehog:latest github --org=redhat-cop --results=verified --fail --exclude-paths /tmp/.github/exclude-patterns.txt
