name: Truffle Hog Secret Detection
on:
  schedule:
    - cron: "0 1 * * MON"
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  hog:
    runs-on: ubuntu-latest
    name: hog
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
      - name: TruffleHog
        run: docker run --rm -v ${{ github.workspace }}:/tmp -w /tmp ghcr.io/trufflesecurity/trufflehog:latest github --org=redhat-cop --results=verified --fail --exclude-paths /tmp/.github/exclude-patterns.txt
