name: Truffle Hog Secret Detection
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  hog:
    runs-on: ubuntu-latest
    name: hog
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: TruffleHog
        run: docker run --rm -v ${{ github.workspace }}:/tmp -w /tmp ghcr.io/trufflesecurity/trufflehog:latest github --org=redhat-cop --results=verified --fail --exclude-paths /tmp/.github/exclude-patterns.txt
